### ISSUE TITLE
Connect Fail not Authorized

### ISSUE THREAD

**Issue by cxllwel** [Larinax999/popdeng-spam#1]
Hi , I found a problem Connect Fail not Authorized I have used the command python checkupdate.py first and it's show me "Found New Update of gateway mqtt new wss://s.popdeng.click:443/data old None
mqtt gateway wss://s.popdeng.click:443/data | topic click id popdeng/clicks"
After that I've  changed the old wss Which is *wss://o.popdeng.click:443/mqtt *
Then i replaced it with *wss://s.popdeng.click:443/data* 
After that when using the command *go run main.go* it's show me Connect Fail not Authorized 
Sorry for my English as it is my second language.🙏🏻

**Comment by Larinax999** [comment]
fixed and it will get url automatically no need to change url in file
